// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATtIK9uBajQt1cj7Beh79tuFeTpPYTuK8',
    appId: '1:864430767794:web:23de73528f7a48c46793ab',
    messagingSenderId: '864430767794',
    projectId: 'tugassembilan-8d8c3',
    authDomain: 'tugassembilan-8d8c3.firebaseapp.com',
    storageBucket: 'tugassembilan-8d8c3.firebasestorage.app',
    measurementId: 'G-CTYKFPG2SR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL5i2glyDtH665NByunCgpyL4-zNYbrx0',
    appId: '1:864430767794:android:c491645782af060a6793ab',
    messagingSenderId: '864430767794',
    projectId: 'tugassembilan-8d8c3',
    storageBucket: 'tugassembilan-8d8c3.firebasestorage.app',
  );
}
